name: Deploy Rails App

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy repository to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "."
        target: "/opt/docker/password-manager"

    - name: Build and deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /opt/docker/password-manager
          docker build -t password-manager .
          docker stop password-manager || true
          docker rm password-manager || true
          docker run -d --name password-manager -p 3000:3000 -e RAILS_MASTER_KEY=${{ secrets.SERVER_MASTERKEY }} password-manager
